### PR TITLE
fix typo and remove any extra whitespace at the end of line

### PR DESCRIPTION
**Pull request by rubenporras**

### CODE REVIEW

**Comment by rubenporras** [comment]
Thanks for explanation and for letting me know that you will put the PR on hold for a moment.

As a heads-up, I am planning to do some work on EMF in the `Pool` class, and I thought it would make any following PR clearer if my IDE does not mix other changes with the code changes.

**Comment by merks** [comment]
Yes that's a good plan.  On Wednesday morning I have a lot of work to do to open the 2025-03 4.35 develop cycle for SimRel, Orbit, EPP, EMF, Oomph, and so on.  So expect some action later in the day...

**Comment by merks** [comment]
Given you've committed what looks like a bit of a scary semantic change, with no explanation or justification why, I will need to look very closely as what is changing and why it's changing.   Moreover, it looks like a thread safe test is failing.

image

Even the heap space errors might well be the result of your changes.

**Comment by rubenporras** [comment]
Sorry, this was a mistake. I did not wanted to push to this branch. I will revert it to the original state.

**Pull request closed without merging**
