### PR TITLE
Remove blank Javadoc

### PR DESCRIPTION
**Pull request by jukzi**
This commit cleans up Javadoc that does not add information. It resolves ecj warnings:
 `Javadoc: Description expected after ...`
It helps to prevent future empty javadoc by disabling missingJavaDoc warnings. This resolves
 `Javadoc: Missing ...`

The modification is a result of regular expression search&replace:

in files `*.java`
 `^[\s]*\*[\s]*(@return|@param[\s]*[^\s]+|@throws[\s]*[^\s]+)\R([\s]*\*[\s]*@|[\s]*\*/\R)`
 ->`$2`
 `^([\s]*\*[\s]*\R)([\s]*\*/\R)`
 ->`$2`
 `^[\S\t ]*/\*\*\R[\s]*\*/\R`
 ->``

in files `org.eclipse.jdt.core.prefs`
 `org\.eclipse\.jdt\.core\.compiler\.problem\.missingJavadoc(Comments|Tags)\=[^\s]*`
 ->`org\.eclipse\.jdt\.core\.compiler\.problem\.missingJavadoc$1\=ignore`

### CODE REVIEW

**Comment by jukzi** [comment]
@merks @HannesWell any chance to merge?

**Review by HannesWell — APPROVED** [review]
LGTM.

But I'm not an EMF committer, so Ed has to decide that eventually.

**Comment by merks** [comment]
Sorry, I need some more time.  I only opened the stream the other day with this commit:

https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/issues/1646

Yesterday I finished the release and traveled to Stuttgart.  Today I am in an all-day meeting (IDE WG) at Vector.   Tomorrow more travel...

**Comment by merks** [comment]
Annoyingly enough, this creates new warnings in my EMF workspace:

image

That's just what I don't need.

**Comment by HannesWell** [comment]
> Yesterday I finished the release and traveled to Stuttgart. 

I'm glad you survived the 'Fernwanderweg' at the Hauptbahnhof Stuttgart 😄

**Comment by HannesWell** [comment]
> Annoyingly enough, this creates new warnings in my EMF workspace:

In other similar clean-ups @jukzi changed the corresponding preference.

**Comment by merks** [comment]
It’s fine. I added semi-obvious comments to make the warnings go away so all is good. Much more annoying are the security manager warnings but that is a different story.

**Comment by jukzi** [comment]
i am sorry, 
why does your emf workspace not respect `missingJavadocTags=ignore`?

**Comment by merks** [comment]
I’m a big non-fan of massive changes that are hard to review.  E.g., I did not notice you added project-specific preferences to a **subset** of the projects.  I don’t want that. I’ll need to revisit that further.

Keep in mind that EMF is not the Platform.  I’m much more conservative about changing things that aren’t broken.  But I also try to remain open minded. 

In any case. Don’t worry, be happy. I am a huge fan of a warning free workspace so I really really appreciate your cleanup efforts in general!!

**Comment by jukzi** [comment]
i guess the other projects take the workspace default and that defaults may be different in your workspace?

**Comment by merks** [comment]
Yes I can set workspace defaults in the setup.  Eclipse is really really poor at supporting consistent project-specific preferences across a large family of projects.  I worked on a tool for that in Oomph but it not possible to do everything I’d like to do.  

As I said, don’t worry be happy.  I don’t mind doing a bit of work to make things better.  Especially in your case when I see how much you do to make neglected things better.

**Pull request merged**
